
<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Usuario;
    //require_once('../app/cci/Cliente.php');
        
    $usuarioCCI = new Usuario();    
    $usuario = $usuarioCCI->findById();    
?>

<h2>Atualizar Cliente</h2>

<form action="index.php?usuario=save&id=<?php echo $usuario['cd_usuario']; ?>" method="post">
  <hr />
  <div class="row">
      
    <div class="form-group col-md-7" hidden="true">      
        <input hidden="id" type="text" class="form-control" name="usuario['cd_usuario']" value="<?php echo $usuario['cd_usuario']; ?>">
    </div>      
      
    <div class="form-group col-md-7">
      <label for="name">Email</label>
      <input type="text" class="form-control" name="usuario['email']" value="<?php echo $usuario['email']; ?>">
    </div>
      
    <div class="form-group col-md-7">
      <label for="name">Password</label>
      <input type="password" class="form-control" name="usuario['password']" value="<?php echo $usuario['password']; ?>">
    </div>

  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <label for="campo2">Tipo de Usuário</label>
      <input type="text" class="form-control" name="usuario['tp_usuario']" value="<?php echo $usuario['tp_usuario']; ?>">
    </div>

    <div class="form-group col-md-2">
      <label for="campo3">Data de Cadastro</label>
      <input type="text" class="form-control" name="usuario['dt_criacao']" disabled value="<?php echo $usuario['dt_criacao']; ?>">
    </div>
  </div>

  </div>
  
  <div id="actions" class="row">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="index.php" class="btn btn-default">Cancelar</a>
    </div>
  </div>
</form>
