<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Usuario;
    //require_once('../app/cci/Cliente.php');
        
    $usuarioCCI = new Usuario();    
    $usuarios = $usuarioCCI->listar(null);
?>

<header>
	<div class="row">
		<div class="col-sm-6">
			<h2>Usuários</h2>
		</div>
		<div class="col-sm-6 text-right h2">
	    	<a class="btn btn-primary" href="?usuario=add"><i class="fa fa-plus"></i> Novo Usuário</a>
	    	<a class="btn btn-default" href="index.php?usuario=getall"><i class="fa fa-refresh"></i> Atualizar</a>
	    </div>
	</div>
</header>

<?php if (!empty($_SESSION['message'])) : ?>
	<div class="alert alert-<?php echo $_SESSION['type']; ?> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo $_SESSION['message']; ?>
	</div>
	<?php clear_messages(); ?>
<?php endif; ?>

<hr>

<table class="table table-hover">
<thead>
	<tr>
		<th>ID</th>
		<th width="30%">Email</th>
		<th>Tipo de Usuário</th>		
		<th>Data de Cadastro</th>
		<th>Opções</th>
	</tr>
</thead>
<tbody>
<?php if ($usuarios) : ?>
<?php foreach ($usuarios as $usuario) : ?>
	<tr>
		<td><?php echo $usuario['cd_usuario']; ?></td>
		<td><?php echo $usuario['email']; ?></td>
		<td><?php echo $usuario['tp_usuario']; ?></td>		
		<td><?php echo $usuario['dt_criacao']; ?></td>
		<td class="actions text-right">
			<a href="?usuario=retrieve&id=<?php echo (int)$usuario['cd_usuario']; ?>" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
			<a href="?usuario=edit&id=<?php echo (int)$usuario['cd_usuario']; ?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
			<a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" data-customer="<?php echo $usuario['cd_usuario']; ?>">
				<i class="fa fa-trash"></i> Excluir
			</a>
		</td>
	</tr>
<?php endforeach; ?>
<?php else : ?>
	<tr>
		<td colspan="6">Nenhum registro encontrado.</td>
	</tr>
<?php endif; ?>
</tbody>
</table>

<?php 
    include ("../app/inc/modal.phtml");     
?>

<?php 
    include ("../app/inc/footer.phtml");     
?>


