<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Combinacao;
    //require_once('../app/cci/Cliente.php');
        
    $combinacaoCCI = new Combinacao();    
    $combinacaos = $combinacaoCCI->listarCombinacao(null);
?>

<header>
	<div class="row">
		<div class="col-sm-6">
			<h2>Combinações</h2>
		</div>
		<div class="col-sm-6 text-right h2">
	    	<a class="btn btn-primary" href="?combinacao=add"><i class="fa fa-plus"></i> Nova Combinação</a>
	    	<a class="btn btn-default" href="index.php?combinacao=getall"><i class="fa fa-refresh"></i> Atualizar</a>
	    </div>
	</div>
</header>

<?php if (!empty($_SESSION['message'])) : ?>
	<div class="alert alert-<?php echo $_SESSION['type']; ?> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo $_SESSION['message']; ?>
	</div>
	<?php clear_messages(); ?>
<?php endif; ?>

<hr>

<table class="table table-hover">
<thead>
	<tr>
		<th>ID</th>
		<th width="30%">Descrição Combinação</th>
		<th>Tipo de Nave</th>		
		<th>Tipo de Arma</th>
		<th>Opções</th>
	</tr>
</thead>
<tbody>
<?php if ($combinacaos) : ?>
<?php foreach ($combinacaos as $combinacao) : ?>
	<tr>
		<td><?php echo $combinacao['cd_combinacao']; ?></td>
		<td><?php echo $combinacao['ds_combinacao']; ?></td>
		<td><?php echo $combinacao['tp_nave']; ?></td>		
		<td><?php echo $combinacao['tp_arma']; ?></td>
		<td class="actions text-right">
			<a href="?combinacao=retrieve&id=<?php echo (int)$combinacao['cd_combinacao']; ?>" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
			<a href="?combinacao=edit&id=<?php echo (int)$combinacao['cd_combinacao']; ?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
			<a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" data-customer="<?php echo $combinacao['cd_combinacao']; ?>">
				<i class="fa fa-trash"></i> Excluir
			</a>
		</td>
	</tr>
<?php endforeach; ?>
<?php else : ?>
	<tr>
		<td colspan="6">Nenhum registro encontrado.</td>
	</tr>
<?php endif; ?>
</tbody>
</table>

<?php 
    include ("../app/inc/modal.phtml");     
?>

<?php 
    include ("../app/inc/footer.phtml");     
?>


