<h1>Dashboard</h1>
<hr />

<div class="row">
	<div class="col-xs-6 col-sm-3 col-md-2">
		<a href="?cliente=add" class="btn btn-primary">
			<div class="row">
				<div class="col-xs-12 text-center">
					<i class="fa fa-plus fa-5x"></i>
				</div>
				<div class="col-xs-12 text-center">
					<p>Novo Usuário</p>
				</div>
			</div>
		</a>
	</div>

	<div class="col-xs-6 col-sm-3 col-md-2">
		<a href="?cliente=getall" class="btn btn-default">
			<div class="row">
				<div class="col-xs-12 text-center">
					<i class="fa fa-user fa-5x"></i>
				</div>
				<div class="col-xs-12 text-center">
					<p>Usuário</p>
				</div>
			</div>
		</a>
	</div>
</div>

<br/>

<div class="row">
	<div class="col-xs-6 col-sm-3 col-md-2">
		<a href="?cliente=add" class="btn btn-primary">
			<div class="row">
				<div class="col-xs-12 text-center">
					<i class="fa fa-plus fa-5x"></i>
				</div>
				<div class="col-xs-12 text-center">
					<p>Novo Cliente</p>
				</div>
			</div>
		</a>
	</div>

	<div class="col-xs-6 col-sm-3 col-md-2">
		<a href="?cliente=getall" class="btn btn-default">
			<div class="row">
				<div class="col-xs-12 text-center">
					<i class="fa fa-gamepad fa-5x"></i>
				</div>
				<div class="col-xs-12 text-center">
					<p>Partidas</p>
				</div>
			</div>
		</a>
	</div>
</div>

<br/>

<?php
    use \app\cci\Servico;
    
    //Testa conexão com banco de dados
    $servico = new Servico();    
?>