<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>:: Viagem Estelar - Settings ::</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    
    <!-- Movimentação do título -->
    <script src="js/util.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="index.php" class="navbar-brand">Viagem Estelar</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Usuários <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?usuario=getall">Gerenciar Usuários</a></li>
                    <li><a href="?usuario=add">Novo Usuário</a></li>
                </ul>                
            </li>
          </ul>
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Partidas <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?partida=getall">Gerenciar Partidas</a></li>
                    <li><a href="?partida=add">Novo Partida (manual)</a></li>
                </ul>                
            </li>
          </ul>            
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Atividades <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?atividade=getall">Gerenciar Atividades</a></li>
                    <li><a href="?atividade=add">Nova Atividade (manual)</a></li>
                </ul>                
            </li>
          </ul> 
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Combinações <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?combinacao=getall">Gerenciar Combinações</a></li>
                    <li><a href="?combinacao=add">Nova Combinação</a></li>
                </ul>                
            </li>
          </ul>     
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Configurações <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?configuracao=getall">Gerenciar Configuração</a></li>
                    <li><a href="?configuracao=add">Nova Configuração</a></li>
                </ul>                
            </li>
          </ul>                
          <ul class="nav navbar-nav">          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Tipos <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="?tipoatividade=getall">Gerenciar Tipos de Atividade</a></li>
                    <li><a href="?tipoatividade=add">Novo Tipo de Atividade</a></li>
                    <li><a href="?tipousuario=getall">Gerenciar Tipos de Usuários</a></li>                    
                    <li><a href="?tiponave=getall">Gerenciar Tipos de Naves</a></li>
                    <li><a href="?tiponave=add">Novo Tipo de Nave</a></li>
                    <li><a href="?tipoarma=getall">Gerenciar Tipos de Armas</a></li>
                    <li><a href="?tipoarma=add">Novo Tipo de Arma</a></li>
                </ul>                
            </li>
          </ul>           
        <div class="navbar-header">
            <a href="index.php?logout=yes" class="navbar-text">Logout</a>
        </div>
        <div class="navbar-header">
            <a href="" class="navbar-brand"><?php echo $_SESSION['usuariosessao']['email']; ?></a>
        </div>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

<main class="container">