<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Tipousuario;
            
    $tipoUsuario = new Tipousuario();    
    $tiposdeusuarios = $tipoUsuario->listar(null);
?>

<header>
	<div class="row">
		<div class="col-sm-6">
			<h2>Tipo de Usuario</h2>
		</div>
		<div class="col-sm-6 text-right h2">
	    	<a class="btn btn-primary" href="?tipousuario=add"><i class="fa fa-plus"></i> Novo Tipo de Usuario</a>
	    	<a class="btn btn-default" href="?tipousuario=getall"><i class="fa fa-refresh"></i> Atualizar</a>
	    </div>
	</div>
</header>

<?php if (!empty($_SESSION['message'])) : ?>
	<div class="alert alert-<?php echo $_SESSION['type']; ?> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo $_SESSION['message']; ?>
	</div>
	<?php clear_messages(); ?>
<?php endif; ?>

<hr>

<table class="table table-hover">
<thead>
	<tr>
		<th>ID</th>
		<th width="30%">Descrição</th>		
		<th>Opções</th>
	</tr>
</thead>
<tbody>
<?php if ($tiposdeusuarios) : ?>
<?php foreach ($tiposdeusuarios as $tipousuario) : ?>
	<tr>
		<td><?php echo $tipousuario['tp_usuario']; ?></td>
		<td><?php echo $tipousuario['ds_tp_usuario']; ?></td>		
		<td class="actions text-right">
			<a href="?tipousuario=retrieve&id=<?php echo (int)$tipousuario['tp_usuario']; ?>" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
			<a href="?tipousuario=edit&id=<?php echo (int)$tipousuario['tp_usuario']; ?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
			<a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" data-customer="<?php echo $tipousuario['tp_usuario']; ?>">
				<i class="fa fa-trash"></i> Excluir
			</a>
		</td>
	</tr>
<?php endforeach; ?>
<?php else : ?>
	<tr>
		<td colspan="6">Nenhum registro encontrado.</td>
	</tr>
<?php endif; ?>
</tbody>
</table>

<?php 
    include ("../app/inc/modal.phtml");     
?>

<?php 
    include ("../app/inc/footer.phtml");     
?>


