<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Atividade;
    //require_once('../app/cci/Cliente.php');
        
    $atividadeCCI = new Atividade();    
    $atividades = $atividadeCCI->listarAtividade(null);
?>

<header>
	<div class="row">
		<div class="col-sm-6">
			<h2>Atividades</h2>
		</div>
		<div class="col-sm-6 text-right h2">
	    	<a class="btn btn-primary" href="?atividade=add"><i class="fa fa-plus"></i> Novo Atividade</a>
	    	<a class="btn btn-default" href="index.php?atividade=getall"><i class="fa fa-refresh"></i> Atualizar</a>
	    </div>
	</div>
</header>

<?php if (!empty($_SESSION['message'])) : ?>
	<div class="alert alert-<?php echo $_SESSION['type']; ?> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo $_SESSION['message']; ?>
	</div>
	<?php clear_messages(); ?>
<?php endif; ?>

<hr>

<table class="table table-hover">
<thead>
	<tr>
		<th>ID</th>
                <th>Data da Atividade</th>
		<th width="30%">Usuário</th>
		<th>Tipo de Atividade</th>				
		<th>Opções</th>
	</tr>
</thead>
<tbody>
<?php if ($atividades) : ?>
<?php foreach ($atividades as $atividade) : ?>
	<tr>
		<td><?php echo $atividade['cd_atividade']; ?></td>
		<td><?php echo $atividade['dt_atividade']; ?></td>
		<td><?php echo $atividade['cd_usuario']; ?></td>		
		<td><?php echo $atividade['tp_atividade']; ?></td>
		<td class="actions text-right">
			<a href="?atividade=retrieve&id=<?php echo (int)$atividade['cd_atividade']; ?>" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
			<a href="?atividade=edit&id=<?php echo (int)$atividade['cd_atividade']; ?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
			<a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" data-customer="<?php echo $atividade['cd_atividade']; ?>">
				<i class="fa fa-trash"></i> Excluir
			</a>
		</td>
	</tr>
<?php endforeach; ?>
<?php else : ?>
	<tr>
		<td colspan="6">Nenhum registro encontrado.</td>
	</tr>
<?php endif; ?>
</tbody>
</table>

<?php 
    include ("../app/inc/modal.phtml");     
?>

<?php 
    include ("../app/inc/footer.phtml");     
?>


