<?php         
    use app\cci\Login;
    //use app\cdp\Usuario;
                
    //$usuario = new Usuario();
    $login = new Login();
    $usuario = $login->loginuser;
    //$usuario = $cliente->listar(null);
?>

<?php include ("../app/inc/headerlogin.phtml"); ?>

  <body>

    <div class="container">

        <form class="form-signin" action="index.php" method="POST">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name="email" value="<?php echo $usuario['email']; ?>" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" value="<?php echo $usuario['password']; ?>" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <!--<button class="btn btn-lg btn-primary btn-block" onclick="return enviaRequisicaoLogin();" type="button" >Sign in</button>-->
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="js/ie10-viewport-bug-workaround.js"></script>-->
  </body>
</html>
