<?php 
  include ("../app/inc/header.phtml");   
  use app\cdp\Tipoarma;
  
  $tipoArmaDominio = new Tipoarma();
  
  $tipoarma = $tipoArmaDominio->retornaAtributosVaziosEmArray();
?>


<h2>Novo Tipo de Arma</h2>

<form action="index.php?tipoarma=insert" method="post">
  <!-- area de campos do form -->
  <hr />
  <div class="row">
    
    <div class="form-group col-md-7">
      <label for="name">Descrição do Tipo de Arma</label>
      <input type="text" class="form-control" name="tipoarma['ds_tp_arma']" value="<?php echo $tipoarma['ds_tp_arma']; ?>">
    </div>

  </div>
  
  <div id="actions" class="row">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="index.php" class="btn btn-default">Cancelar</a>
    </div>
  </div>
</form>