
<?php 
  //require_once('functions.php'); 
  //add();
?>

<?php 
    include ("../app/inc/header.phtml"); 
?>

<h2>Novo Tipo de Arma</h2>

<form action="add.php" method="post">
  <!-- area de campos do form -->
  <hr />
  <div class="row">
    
      <div class="form-group col-md-7">
      <label for="name">Descrição do Tipo de Arama</label>
      <input type="text" class="form-control" name="tipoarma['ds_tp_arama']">
    </div>

  </div>
  
  <div id="actions" class="row">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="index.php" class="btn btn-default">Cancelar</a>
    </div>
  </div>
</form>

<?php include ("../app/inc/footer.phtml"); ?>