<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Tipoarma;
            
    $tipoArmaCCI = new Tipoarma();    
    
    $tipoarma = $tipoArmaCCI->findById();
?>

<h2>Atualizar Tipo de Arma</h2>

<form action="index.php?tipoarma=save&id=<?php echo $tipoarma['tp_arma']; ?>" method="post">
  <hr />
  <div class="row">
      
    <div class="form-group col-md-7" hidden="true">      
        <input hidden="id" type="text" class="form-control" name="tipoarma['tp_arma']" value="<?php echo $tipoarma['tp_arma']; ?>">
    </div>      
      
    <div class="form-group col-md-7">
      <label for="name">Descrição do Tipo de Arma</label>
      <input type="text" class="form-control" name="tipoarma['ds_tp_arma']" value="<?php echo $tipoarma['ds_tp_arma']; ?>">
    </div>
    
  </div>
  <div id="actions" class="row">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="index.php" class="btn btn-default">Cancelar</a>
    </div>
  </div>
</form>