<?php 
    include ("../app/inc/header.phtml"); 
    use app\cci\Tipoarma;
            
    $tipoArma = new Tipoarma();    
    $tiposdearmas = $tipoArma->listar(null);
?>

<header>
	<div class="row">
		<div class="col-sm-6">
			<h2>Tipo de Arma</h2>
		</div>
		<div class="col-sm-6 text-right h2">
	    	<a class="btn btn-primary" href="?tipoarma=add"><i class="fa fa-plus"></i> Novo Tipo de Arma</a>
	    	<a class="btn btn-default" href="?tipoarma=getall"><i class="fa fa-refresh"></i> Atualizar</a>
	    </div>
	</div>
</header>

<?php if (!empty($_SESSION['message'])) : ?>
	<div class="alert alert-<?php echo $_SESSION['type']; ?> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo $_SESSION['message']; ?>
	</div>
	<?php clear_messages(); ?>
<?php endif; ?>

<hr>

<table class="table table-hover">
<thead>
	<tr>
		<th>ID</th>
		<th width="30%">Descrição</th>		
		<th>Opções</th>
	</tr>
</thead>
<tbody>
<?php if ($tiposdearmas) : ?>
<?php foreach ($tiposdearmas as $tipoarma) : ?>
	<tr>
		<td><?php echo $tipoarma['tp_arma']; ?></td>
		<td><?php echo $tipoarma['ds_tp_arma']; ?></td>		
		<td class="actions text-right">
			<a href="?tipoarma=retrieve&id=<?php echo (int)$tipoarma['tp_arma']; ?>" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
			<a href="?tipoarma=edit&id=<?php echo (int)$tipoarma['tp_arma']; ?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
			<a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" data-customer="<?php echo $tipoarma['tp_arma']; ?>">
				<i class="fa fa-trash"></i> Excluir
			</a>
		</td>
	</tr>
<?php endforeach; ?>
<?php else : ?>
	<tr>
		<td colspan="6">Nenhum registro encontrado.</td>
	</tr>
<?php endif; ?>
</tbody>
</table>

<?php 
    include ("../app/inc/modal.phtml");     
?>

<?php 
    include ("../app/inc/footer.phtml");     
?>


